version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trillion-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v1832tu0wbh7"
s3_prefix = "trillion-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
